remote: https://www.99bill.com/gateway/recvMerchantInfoAction.htm
rsa:
  pem_path: 99bill-rsa.pem
  password: 123456
  cer_path: 99bill-rsa.cer

params:
  merchant_acct_id: 1002301545701
  version: v2.0
  language: 1
  sign_type: 4
